### ISSUE TITLE
试用了一下

### ISSUE THREAD

**Issue by wtjperi2003** [violetiu/yuanliu#1]
内容做的挺强大的。赞一个。不过这种功能似乎没办法推广试用。开发里基本没可能用。定位上可能需要改一下。目前这样的项目，似乎做一个产品原型设计是相对靠谱的，像墨刀，摹客那样的

**Comment by violetiu** [comment]
确实是没法推广，主要是为了解决自己画原型中的一些麻烦，加快画的速度，也能以原型充当产品演示。
